apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Abhiabhi1019/my-microk8s-devops-project.git
    targetRevision: main
    path: helm/node-app

  destination:
    server: https://kubernetes.default.svc
    namespace: node-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
