replicaCount: 1

image:
  repository: localhost:32000/node-app
  tag: "1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: public
  annotations: {}
  hosts:
    - host: mynode.local
      paths:
        - /
