apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "myapp.name" . }}
  ports:
    - port: {{ .Values.service.port }}   # external service port
      targetPort: 3000                   # container port (internal)
      protocol: TCP
