controller:
  JCasC:
    enabled: false

  sidecars:
    configAutoReload:
      enabled: false

  installPlugins:
    - kubernetes:4263.v70db_98349057
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.4.3
    - configuration-as-code:1810.v9b_c30a_249a_4
